# Generated by Django 5.2.8 on 2025-12-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("universe", "0001_initial"),
        ("universe", "0002_remove_actor_prompt_remove_actor_prompt_identity_and_more"),
        ("universe", "0003_controller_location"),
        ("universe", "0004_dialogueeventlog"),
        ("universe", "0005_remove_actor_role_field"),
        ("universe", "0006_add_celestial_physicalbody_models"),
        ("universe", "0007_update_color_palette_to_dataclass"),
        ("universe", "0008_planet_orbital_distance_au_star_temperature_k"),
        ("universe", "0009_starsystem_system_age_years"),
        ("universe", "0010_atmosphere"),
        (
            "universe",
            "0011_moon_albedo_moon_axial_tilt_deg_moon_color_palette_and_more",
        ),
        ("universe", "0012_rename_moon_variety_to_moon_type"),
        ("universe", "0013_alter_moon_moon_type"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("voice_template", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "scale",
                    models.CharField(
                        choices=[
                            ("GX", "galaxy"),
                            ("SY", "star system"),
                            ("SR", "star"),
                            ("PL", "planet"),
                            ("MN", "moon"),
                            ("SS", "space station"),
                        ],
                        default="SS",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.actor",
                    ),
                ),
            ],
            bases=("universe.actor",),
        ),
        migrations.CreateModel(
            name="Galaxy",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                (
                    "galaxy_type",
                    models.CharField(
                        choices=[
                            ("CD", "Supergiant Elliptical Type cD"),
                            ("DW", "Dwarf"),
                            ("E0", "Elliptical - Sphere"),
                            ("E7", "Elliptical - Elongated"),
                            ("IR", "Irregular Type i"),
                            ("IT", "Irregular Type ii"),
                            ("LN", "Lenticular"),
                            ("SB", "Barred Spiral"),
                            ("SH", "Elliptical Shell"),
                            ("SP", "Spiral Arm"),
                            ("SS", "Superluminous Spiral"),
                            ("UD", "Ultra Diffuse"),
                        ],
                        default="SP",
                        max_length=2,
                    ),
                ),
                (
                    "galaxy_size",
                    models.CharField(
                        choices=[
                            ("D", "dwarf"),
                            ("S", "small"),
                            ("M", "medium"),
                            ("L", "large"),
                            ("X", "extra large"),
                            ("G", "supergiant"),
                        ],
                        default="L",
                        max_length=1,
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "small"), ("M", "medium"), ("L", "large")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        help_text="Current cargo being transported",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DOCK", "Docked"),
                            ("TRAN", "In Transit"),
                            ("APRCH", "Approaching"),
                            ("HOLD", "Holding Pattern"),
                            ("DEPT", "Departing"),
                        ],
                        default="DOCK",
                        max_length=5,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ships_present",
                        to="universe.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.actor",
                    ),
                ),
                (
                    "ship",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pilot",
                        to="universe.ship",
                    ),
                ),
            ],
            bases=("universe.actor",),
        ),
        migrations.CreateModel(
            name="StarSystem",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                (
                    "orbits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star_systems",
                        to="universe.galaxy",
                    ),
                ),
                (
                    "system_age_years",
                    models.FloatField(
                        blank=True,
                        help_text="System age in years (derived from seed, shared by all bodies in system)",
                        null=True,
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                ("large_berths", models.PositiveSmallIntegerField(default=1)),
                ("medium_berths", models.PositiveSmallIntegerField(default=2)),
                ("small_berths", models.PositiveSmallIntegerField(default=8)),
                (
                    "orbits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orbiting_stations",
                        to="universe.location",
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
        migrations.CreateModel(
            name="BerthAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "berth_size",
                    models.CharField(
                        choices=[("L", "Large"), ("M", "Medium"), ("S", "Small")],
                        max_length=1,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ship",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_berth",
                        to="universe.ship",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_berths",
                        to="universe.station",
                    ),
                ),
            ],
            options={
                "unique_together": {("station", "ship")},
            },
        ),
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "actor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.actor",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controller",
                        to="universe.location",
                    ),
                ),
            ],
            bases=("universe.actor",),
        ),
        migrations.CreateModel(
            name="DialogueEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.FloatField(help_text="Simulation time when event occurred"),
                ),
                (
                    "actor_name",
                    models.CharField(
                        help_text="Name of the speaking actor", max_length=200
                    ),
                ),
                ("text", models.TextField(help_text="The dialogue message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Database insertion time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dialogue Event Log",
                "verbose_name_plural": "Dialogue Event Logs",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="universe_di_timesta_0e612e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                ("star_type", models.CharField(default="G2V", max_length=10)),
                (
                    "star_magnitude",
                    models.DecimalField(decimal_places=2, default=4.31, max_digits=8),
                ),
                (
                    "orbits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stars",
                        to="universe.starsystem",
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                        null=True,
                    ),
                ),
                (
                    "mass_kg",
                    models.FloatField(
                        blank=True, help_text="Mass in kilograms", null=True
                    ),
                ),
                (
                    "mass_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Mass in solar masses (calculated from mass_kg)",
                        null=True,
                    ),
                ),
                (
                    "radius_km",
                    models.FloatField(
                        blank=True, help_text="Radius in kilometers", null=True
                    ),
                ),
                (
                    "radius_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Radius in solar radii (calculated from radius_km)",
                        null=True,
                    ),
                ),
                (
                    "temperature_k",
                    models.FloatField(
                        blank=True, help_text="Surface temperature in Kelvin", null=True
                    ),
                ),
                (
                    "albedo",
                    models.FloatField(
                        blank=True, help_text="Bond albedo (0.0-1.0)", null=True
                    ),
                ),
                (
                    "axial_tilt_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Axial tilt in degrees (rotation axis tilt)",
                        null=True,
                    ),
                ),
                (
                    "density_kg_m3",
                    models.FloatField(
                        blank=True, help_text="Density in kg/m³", null=True
                    ),
                ),
                (
                    "equilibrium_temperature_k",
                    models.FloatField(
                        blank=True,
                        help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                        null=True,
                    ),
                ),
                (
                    "is_tidally_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the body is tidally locked to its parent",
                    ),
                ),
                (
                    "orbital_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Semi-major axis in km (for moons)",
                        null=True,
                    ),
                ),
                (
                    "orbital_eccentricity",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                        null=True,
                    ),
                ),
                (
                    "orbital_inclination_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                        null=True,
                    ),
                ),
                (
                    "orbital_period_days",
                    models.FloatField(
                        blank=True, help_text="Orbital period in Earth days", null=True
                    ),
                ),
                (
                    "orbital_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital period in hours (for moons)",
                        null=True,
                    ),
                ),
                (
                    "rotation_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Rotation period (day length) in hours",
                        null=True,
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
        migrations.CreateModel(
            name="Atmosphere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "atmosphere_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CO2_THIN", "CO₂ Thin"),
                            ("CO2_THICK", "CO₂ Thick"),
                            ("N2_O2", "N₂/O₂ (Earth-like)"),
                            ("N2", "Nitrogen"),
                            ("H2_HE", "H₂/He (Gas Giant)"),
                            ("N2_CH4", "N₂/CH₄ (Titan-like)"),
                            ("SO2", "SO₂ (Volcanic)"),
                            ("H2O", "H₂O (Steam)"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "atmosphere_height_km",
                    models.FloatField(
                        blank=True,
                        help_text="Height of atmosphere above surface in kilometers",
                        null=True,
                    ),
                ),
                (
                    "surface_pressure_bar",
                    models.FloatField(
                        blank=True,
                        help_text="Surface atmospheric pressure in bars",
                        null=True,
                    ),
                ),
                (
                    "scale_height_km",
                    models.FloatField(
                        blank=True,
                        help_text="Atmospheric scale height (density falloff) in kilometers",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                (
                    "planet_type",
                    models.CharField(
                        choices=[
                            ("MP", "Mesoplanet"),
                            ("SI", "Silicate"),
                            ("TE", "Terrestrial"),
                            ("SE", "Super-earth"),
                            ("CT", "Cthonian"),
                            ("IG", "Ice Giant"),
                            ("GG", "Gas Giant"),
                            ("AB", "Asteroid Belt"),
                        ],
                        default="TE",
                        max_length=2,
                    ),
                ),
                (
                    "orbits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planets",
                        to="universe.star",
                    ),
                ),
                (
                    "orbital_distance_au",
                    models.FloatField(
                        blank=True, help_text="Semi-major axis in AU", null=True
                    ),
                ),
                (
                    "albedo",
                    models.FloatField(
                        blank=True, help_text="Bond albedo (0.0-1.0)", null=True
                    ),
                ),
                (
                    "axial_tilt_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Axial tilt in degrees (rotation axis tilt)",
                        null=True,
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                        null=True,
                    ),
                ),
                (
                    "density_kg_m3",
                    models.FloatField(
                        blank=True, help_text="Density in kg/m³", null=True
                    ),
                ),
                (
                    "equilibrium_temperature_k",
                    models.FloatField(
                        blank=True,
                        help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                        null=True,
                    ),
                ),
                (
                    "is_tidally_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the body is tidally locked to its parent",
                    ),
                ),
                (
                    "mass_kg",
                    models.FloatField(
                        blank=True, help_text="Mass in kilograms", null=True
                    ),
                ),
                (
                    "mass_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Mass in solar masses (calculated from mass_kg)",
                        null=True,
                    ),
                ),
                (
                    "orbital_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Semi-major axis in km (for moons)",
                        null=True,
                    ),
                ),
                (
                    "orbital_eccentricity",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                        null=True,
                    ),
                ),
                (
                    "orbital_inclination_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                        null=True,
                    ),
                ),
                (
                    "orbital_period_days",
                    models.FloatField(
                        blank=True, help_text="Orbital period in Earth days", null=True
                    ),
                ),
                (
                    "orbital_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital period in hours (for moons)",
                        null=True,
                    ),
                ),
                (
                    "radius_km",
                    models.FloatField(
                        blank=True, help_text="Radius in kilometers", null=True
                    ),
                ),
                (
                    "radius_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Radius in solar radii (calculated from radius_km)",
                        null=True,
                    ),
                ),
                (
                    "rotation_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Rotation period (day length) in hours",
                        null=True,
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
        migrations.CreateModel(
            name="Moon",
            fields=[
                (
                    "location_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="universe.location",
                    ),
                ),
                (
                    "moon_type",
                    models.CharField(
                        choices=[
                            ("R", "Rocky"),
                            ("I", "Icy"),
                            ("O", "Organic"),
                            ("T", "Terrestrial"),
                        ],
                        default="R",
                        help_text="The primary composition/type of the moon",
                        max_length=1,
                    ),
                ),
                (
                    "orbits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moons",
                        to="universe.location",
                    ),
                ),
                (
                    "albedo",
                    models.FloatField(
                        blank=True, help_text="Bond albedo (0.0-1.0)", null=True
                    ),
                ),
                (
                    "axial_tilt_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Axial tilt in degrees (rotation axis tilt)",
                        null=True,
                    ),
                ),
                (
                    "color_palette",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                        null=True,
                    ),
                ),
                (
                    "density_kg_m3",
                    models.FloatField(
                        blank=True, help_text="Density in kg/m³", null=True
                    ),
                ),
                (
                    "equilibrium_temperature_k",
                    models.FloatField(
                        blank=True,
                        help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                        null=True,
                    ),
                ),
                (
                    "is_tidally_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the body is tidally locked to its parent",
                    ),
                ),
                (
                    "mass_kg",
                    models.FloatField(
                        blank=True, help_text="Mass in kilograms", null=True
                    ),
                ),
                (
                    "mass_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Mass in solar masses (calculated from mass_kg)",
                        null=True,
                    ),
                ),
                (
                    "orbital_distance_km",
                    models.FloatField(
                        blank=True,
                        help_text="Semi-major axis in km (for moons)",
                        null=True,
                    ),
                ),
                (
                    "orbital_eccentricity",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                        null=True,
                    ),
                ),
                (
                    "orbital_inclination_deg",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                        null=True,
                    ),
                ),
                (
                    "orbital_period_days",
                    models.FloatField(
                        blank=True, help_text="Orbital period in Earth days", null=True
                    ),
                ),
                (
                    "orbital_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Orbital period in hours (for moons)",
                        null=True,
                    ),
                ),
                (
                    "radius_km",
                    models.FloatField(
                        blank=True, help_text="Radius in kilometers", null=True
                    ),
                ),
                (
                    "radius_solar",
                    models.FloatField(
                        blank=True,
                        help_text="Radius in solar radii (calculated from radius_km)",
                        null=True,
                    ),
                ),
                (
                    "rotation_period_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Rotation period (day length) in hours",
                        null=True,
                    ),
                ),
            ],
            bases=("universe.location",),
        ),
    ]
