# Generated by Django 5.1.6 on 2025-03-04 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('PILOT', 'Pilot'), ('CONTROLLER', 'Controller'), ('SATELLITE', 'Satellite')], max_length=20)),
                ('traits', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('voice_template', models.CharField(blank=True, max_length=100)),
                ('prompt_identity', models.TextField(blank=True)),
                ('prompt_instructions', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scale', models.CharField(choices=[('GX', 'galaxy'), ('SY', 'star system'), ('SR', 'star'), ('PL', 'planet'), ('MN', 'moon'), ('SS', 'space station')], default='SS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.actor')),
            ],
            bases=('universe.actor',),
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.actor')),
            ],
            bases=('universe.actor',),
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('galaxy_type', models.CharField(choices=[('CD', 'Supergiant Elliptical Type cD'), ('DW', 'Dwarf'), ('E0', 'Elliptical - Sphere'), ('E7', 'Elliptical - Elongated'), ('IR', 'Irregular Type i'), ('IT', 'Irregular Type ii'), ('LN', 'Lenticular'), ('SB', 'Barred Spiral'), ('SH', 'Elliptical Shell'), ('SP', 'Spiral Arm'), ('SS', 'Superluminous Spiral'), ('UD', 'Ultra Diffuse')], default='SP', max_length=2)),
                ('galaxy_size', models.CharField(choices=[('D', 'dwarf'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('X', 'extra large'), ('G', 'supergiant')], default='L', max_length=1)),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('star_type', models.CharField(default='G2V', max_length=10)),
                ('star_magnitude', models.DecimalField(decimal_places=2, default=4.31, max_digits=8)),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='M', max_length=1)),
                ('cargo', models.CharField(blank=True, help_text='Current cargo being transported', max_length=100, null=True)),
                ('status', models.CharField(choices=[('DOCK', 'Docked'), ('TRAN', 'In Transit'), ('APRCH', 'Approaching'), ('HOLD', 'Holding Pattern'), ('DEPT', 'Departing')], default='DOCK', max_length=5)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ships_present', to='universe.location')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.actor')),
                ('ship', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot', to='universe.ship')),
            ],
            bases=('universe.actor',),
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('variety', models.CharField(choices=[('R', 'Rocky'), ('I', 'Icy'), ('O', 'Organic'), ('T', 'Terrestrial')], default='R', help_text='The primary composition of the moon', max_length=1)),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moons', to='universe.location')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('planet_type', models.CharField(choices=[('MP', 'Mesoplanet'), ('SI', 'Silicate'), ('TE', 'Terrestrial'), ('SE', 'Super-earth'), ('CT', 'Cthonian'), ('IG', 'Ice Giant'), ('GG', 'Gas Giant'), ('AB', 'Asteroid Belt')], default='TE', max_length=2)),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='universe.star')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_systems', to='universe.galaxy')),
            ],
            bases=('universe.location',),
        ),
        migrations.AddField(
            model_name='star',
            name='orbits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='universe.starsystem'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('large_berths', models.PositiveSmallIntegerField(default=1)),
                ('medium_berths', models.PositiveSmallIntegerField(default=2)),
                ('small_berths', models.PositiveSmallIntegerField(default=8)),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbiting_stations', to='universe.location')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='BerthAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berth_size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_berth', to='universe.ship')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_berths', to='universe.station')),
            ],
            options={
                'unique_together': {('station', 'ship')},
            },
        ),
    ]
