# Generated by Django 4.1 on 2022-09-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=64)),
                ('scale', models.CharField(choices=[('GX', 'galaxy'), ('SY', 'star system'), ('SR', 'star'), ('PL', 'planet'), ('MN', 'moon'), ('SS', 'space station')], default='SS', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('type', models.CharField(choices=[('CD', 'Supergiant Elliptical Type cD'), ('DW', 'Dwarf'), ('E0', 'Elliptical - Sphere'), ('E7', 'Elliptical - Elongated'), ('IR', 'Irregular Type i'), ('IT', 'Irregular Type ii'), ('LN', 'Lenticular'), ('SB', 'Barred Spiral'), ('SH', 'Elliptical Shell'), ('SP', 'Spiral Arm'), ('SS', 'Superluminous Spiral'), ('UD', 'Ultra Diffuse')], max_length=2)),
                ('size', models.CharField(choices=[('D', 'dwarf'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('X', 'extra large'), ('G', 'supergiant')], max_length=1)),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('large_berths', models.PositiveSmallIntegerField(default=1)),
                ('medium_berths', models.PositiveSmallIntegerField(default=2)),
                ('small_berths', models.PositiveSmallIntegerField(default=8)),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orbiter', to='universe.location')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='universe.galaxy')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('startype', models.CharField(choices=[('O', 'O-Type Blue Supergiant'), ('B', 'B-Type Blue Giant'), ('A', 'A-Type White Star'), ('F', 'F-Type White Star'), ('G', 'G-Type Yellow Star'), ('K', 'K-Type Yellow Star'), ('M', 'M-Type Red Dwarf'), ('N', 'M-Type Red Supergiant')], max_length=2)),
                ('starmagnitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='universe.starsystem')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='universe.star')),
            ],
            bases=('universe.location',),
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='universe.location')),
                ('orbits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='universe.planet')),
            ],
            bases=('universe.location',),
        ),
    ]
