# Generated by Django 5.1.6 on 2025-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='prompt_identity',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='prompt_instructions',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.CharField(choices=[('PILOT', 'PILOT'), ('CONTROLLER', 'CONTROLLER'), ('SATELLITE', 'SATELLITE')], max_length=20),
        ),
    ]
