# Generated by Django 4.1 on 2022-09-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='planettype',
            field=models.CharField(choices=[('MP', 'Mesoplanet'), ('SI', 'Silicate'), ('TE', 'Terrestrial'), ('SE', 'Super-earth'), ('CT', 'Cthonian'), ('IG', 'Ice Giant'), ('GG', 'Gas Giant'), ('AB', 'Asteroid Belt')], default='TE', max_length=2),
        ),
        migrations.AlterField(
            model_name='moon',
            name='orbits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orbiting', to='universe.planet'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orbiting', to='universe.star'),
        ),
        migrations.AlterField(
            model_name='star',
            name='orbits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Belongs', to='universe.starsystem'),
        ),
        migrations.AlterField(
            model_name='star',
            name='starmagnitude',
            field=models.DecimalField(decimal_places=2, default=4.31, max_digits=8),
        ),
    ]
