# Generated by Django 5.1.6 on 2025-02-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_planet_planettype_alter_moon_orbits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starsystem',
            name='orbits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Belongs', to='universe.galaxy'),
        ),
    ]
