# Generated by Django 5.1.6 on 2025-03-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_remove_actor_prompt_remove_actor_prompt_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller', to='universe.location'),
        ),
    ]
