# Generated by Django 5.2.8 on 2025-11-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0003_controller_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogueEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.FloatField(help_text="Simulation time when event occurred"),
                ),
                (
                    "actor_name",
                    models.CharField(
                        help_text="Name of the speaking actor", max_length=200
                    ),
                ),
                ("text", models.TextField(help_text="The dialogue message")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Database insertion time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dialogue Event Log",
                "verbose_name_plural": "Dialogue Event Logs",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="universe_di_timesta_0e612e_idx"
                    )
                ],
            },
        ),
    ]
