# Generated by Django 5.2.8 on 2025-12-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0004_dialogueeventlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="role",
        ),
    ]
