# Generated by Django 5.2.8 on 2025-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0005_remove_actor_role_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="color_palette",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="mass_kg",
            field=models.FloatField(
                blank=True, help_text="Mass in kilograms", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="mass_solar",
            field=models.FloatField(
                blank=True,
                help_text="Mass in solar masses (calculated from mass_kg)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="radius_km",
            field=models.FloatField(
                blank=True, help_text="Radius in kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="radius_solar",
            field=models.FloatField(
                blank=True,
                help_text="Radius in solar radii (calculated from radius_km)",
                null=True,
            ),
        ),
    ]
