# Generated by Django 5.2.8 on 2025-12-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0006_add_celestial_physicalbody_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='pattern_type',
        ),
        migrations.AlterField(
            model_name='star',
            name='color_palette',
            field=models.JSONField(blank=True, default=dict, help_text='ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}', null=True),
        ),
    ]
