# Generated by Django 5.2.8 on 2025-12-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0007_update_color_palette_to_dataclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="orbital_distance_au",
            field=models.FloatField(
                blank=True, help_text="Semi-major axis in AU", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="temperature_k",
            field=models.FloatField(
                blank=True, help_text="Surface temperature in Kelvin", null=True
            ),
        ),
    ]
