# Generated by Django 5.2.8 on 2025-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0008_planet_orbital_distance_au_star_temperature_k"),
    ]

    operations = [
        migrations.AddField(
            model_name="starsystem",
            name="system_age_years",
            field=models.FloatField(
                blank=True,
                help_text="System age in years (derived from seed, shared by all bodies in system)",
                null=True,
            ),
        ),
    ]
