# Generated by Django 5.2.8 on 2025-12-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("universe", "0009_starsystem_system_age_years"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atmosphere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "atmosphere_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("CO2_THIN", "CO₂ Thin"),
                            ("CO2_THICK", "CO₂ Thick"),
                            ("N2_O2", "N₂/O₂ (Earth-like)"),
                            ("N2", "Nitrogen"),
                            ("H2_HE", "H₂/He (Gas Giant)"),
                            ("N2_CH4", "N₂/CH₄ (Titan-like)"),
                            ("SO2", "SO₂ (Volcanic)"),
                            ("H2O", "H₂O (Steam)"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "atmosphere_height_km",
                    models.FloatField(
                        blank=True,
                        help_text="Height of atmosphere above surface in kilometers",
                        null=True,
                    ),
                ),
                (
                    "surface_pressure_bar",
                    models.FloatField(
                        blank=True,
                        help_text="Surface atmospheric pressure in bars",
                        null=True,
                    ),
                ),
                (
                    "scale_height_km",
                    models.FloatField(
                        blank=True,
                        help_text="Atmospheric scale height (density falloff) in kilometers",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
