# Generated by Django 5.2.8 on 2025-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0010_atmosphere"),
    ]

    operations = [
        migrations.AddField(
            model_name="moon",
            name="albedo",
            field=models.FloatField(
                blank=True, help_text="Bond albedo (0.0-1.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="axial_tilt_deg",
            field=models.FloatField(
                blank=True,
                help_text="Axial tilt in degrees (rotation axis tilt)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="color_palette",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="density_kg_m3",
            field=models.FloatField(
                blank=True, help_text="Density in kg/m³", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="equilibrium_temperature_k",
            field=models.FloatField(
                blank=True,
                help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="is_tidally_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether the body is tidally locked to its parent",
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="mass_kg",
            field=models.FloatField(
                blank=True, help_text="Mass in kilograms", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="mass_solar",
            field=models.FloatField(
                blank=True,
                help_text="Mass in solar masses (calculated from mass_kg)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="orbital_distance_km",
            field=models.FloatField(
                blank=True, help_text="Semi-major axis in km (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="orbital_eccentricity",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="orbital_inclination_deg",
            field=models.FloatField(
                blank=True,
                help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="orbital_period_days",
            field=models.FloatField(
                blank=True, help_text="Orbital period in Earth days", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="orbital_period_hours",
            field=models.FloatField(
                blank=True, help_text="Orbital period in hours (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="radius_km",
            field=models.FloatField(
                blank=True, help_text="Radius in kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="radius_solar",
            field=models.FloatField(
                blank=True,
                help_text="Radius in solar radii (calculated from radius_km)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moon",
            name="rotation_period_hours",
            field=models.FloatField(
                blank=True, help_text="Rotation period (day length) in hours", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="albedo",
            field=models.FloatField(
                blank=True, help_text="Bond albedo (0.0-1.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="axial_tilt_deg",
            field=models.FloatField(
                blank=True,
                help_text="Axial tilt in degrees (rotation axis tilt)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="color_palette",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="ColorPalette dataclass as JSON: {main_color, hex_colors, pattern_name}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="density_kg_m3",
            field=models.FloatField(
                blank=True, help_text="Density in kg/m³", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="equilibrium_temperature_k",
            field=models.FloatField(
                blank=True,
                help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="is_tidally_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether the body is tidally locked to its parent",
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="mass_kg",
            field=models.FloatField(
                blank=True, help_text="Mass in kilograms", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="mass_solar",
            field=models.FloatField(
                blank=True,
                help_text="Mass in solar masses (calculated from mass_kg)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbital_distance_km",
            field=models.FloatField(
                blank=True, help_text="Semi-major axis in km (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbital_eccentricity",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbital_inclination_deg",
            field=models.FloatField(
                blank=True,
                help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbital_period_days",
            field=models.FloatField(
                blank=True, help_text="Orbital period in Earth days", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="orbital_period_hours",
            field=models.FloatField(
                blank=True, help_text="Orbital period in hours (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="radius_km",
            field=models.FloatField(
                blank=True, help_text="Radius in kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="radius_solar",
            field=models.FloatField(
                blank=True,
                help_text="Radius in solar radii (calculated from radius_km)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planet",
            name="rotation_period_hours",
            field=models.FloatField(
                blank=True, help_text="Rotation period (day length) in hours", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="albedo",
            field=models.FloatField(
                blank=True, help_text="Bond albedo (0.0-1.0)", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="axial_tilt_deg",
            field=models.FloatField(
                blank=True,
                help_text="Axial tilt in degrees (rotation axis tilt)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="density_kg_m3",
            field=models.FloatField(
                blank=True, help_text="Density in kg/m³", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="equilibrium_temperature_k",
            field=models.FloatField(
                blank=True,
                help_text="Equilibrium temperature in Kelvin (calculated from star distance/albedo)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="is_tidally_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether the body is tidally locked to its parent",
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="orbital_distance_km",
            field=models.FloatField(
                blank=True, help_text="Semi-major axis in km (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="orbital_eccentricity",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="Orbital eccentricity (0.0=circular, 0.0-1.0=elliptical)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="orbital_inclination_deg",
            field=models.FloatField(
                blank=True,
                help_text="Orbital inclination in degrees (tilt relative to reference plane)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="orbital_period_days",
            field=models.FloatField(
                blank=True, help_text="Orbital period in Earth days", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="orbital_period_hours",
            field=models.FloatField(
                blank=True, help_text="Orbital period in hours (for moons)", null=True
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="rotation_period_hours",
            field=models.FloatField(
                blank=True, help_text="Rotation period (day length) in hours", null=True
            ),
        ),
    ]
