# Generated by Django 5.2.8 on 2025-12-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0012_rename_moon_variety_to_moon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moon",
            name="moon_type",
            field=models.CharField(
                choices=[
                    ("R", "Rocky"),
                    ("I", "Icy"),
                    ("O", "Organic"),
                    ("T", "Terrestrial"),
                ],
                default="R",
                help_text="The primary composition/type of the moon",
                max_length=1,
            ),
        ),
    ]
