# Generated by Django 5.1.6 on 2025-12-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0001_initial_squashed_0013_alter_moon_moon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="starsystem",
            name="galactic_x_ly",
            field=models.FloatField(
                blank=True,
                help_text="Galactic X coordinate in light-years (relative to galactic center)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="starsystem",
            name="galactic_y_ly",
            field=models.FloatField(
                blank=True,
                help_text="Galactic Y coordinate in light-years (relative to galactic center)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="starsystem",
            name="galactic_z_ly",
            field=models.FloatField(
                blank=True,
                help_text="Galactic Z coordinate in light-years (relative to galactic center, perpendicular to plane)",
                null=True,
            ),
        ),
    ]
