# Generated by Django 5.1.6 on 2025-12-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0014_add_galactic_coordinates_to_starsystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_sim_time",
                    models.FloatField(
                        default=0.0, help_text="Simulation time at the anchor point"
                    ),
                ),
                (
                    "anchor_wall_clock",
                    models.FloatField(
                        help_text="Wall-clock Unix timestamp at the anchor point"
                    ),
                ),
                (
                    "time_scale",
                    models.FloatField(
                        default=1.0,
                        help_text="Time multiplier (1.0 = real-time, 60 = 1 min real = 1 hour sim)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation State",
                "verbose_name_plural": "Simulation State",
            },
        ),
    ]
