# Generated by Django 5.1.6 on 2025-12-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0015_add_simulation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
