# Generated by Django 5.1.6 on 2025-12-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0016_make_location_name_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_tone_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include room tone (engine rumble + reverb) in audio",
                    ),
                ),
                (
                    "engine_rumble_base_freq_hz",
                    models.FloatField(
                        default=60.0,
                        help_text="Base frequency for engine rumble (lower = larger ship, typically 20-200 Hz)",
                    ),
                ),
                (
                    "engine_rumble_harmonics",
                    models.IntegerField(
                        default=3,
                        help_text="Number of harmonic frequencies to add to rumble (more = richer sound)",
                    ),
                ),
                (
                    "engine_rumble_intensity",
                    models.FloatField(
                        default=0.3, help_text="Rumble amplitude (0.0 to 1.0+)"
                    ),
                ),
                (
                    "reverb_delay_ms",
                    models.FloatField(
                        default=50.0,
                        help_text="Initial reverb delay in milliseconds (larger = bigger room)",
                    ),
                ),
                (
                    "reverb_decay_factor",
                    models.FloatField(
                        default=0.5,
                        help_text="Reverb decay factor (0.0-1.0, lower = longer tail)",
                    ),
                ),
                (
                    "reverb_room_size_hint",
                    models.CharField(
                        choices=[
                            ("small", "Small cockpit"),
                            ("medium", "Medium cockpit"),
                            ("large", "Large cockpit"),
                            ("station", "Station/control room"),
                        ],
                        default="medium",
                        help_text="Room size hint (affects reverb characteristics)",
                        max_length=20,
                    ),
                ),
                (
                    "static_intensity",
                    models.FloatField(
                        default=0.2, help_text="Static noise intensity (0.0 to 1.0+)"
                    ),
                ),
                (
                    "static_lowpass_hz",
                    models.FloatField(
                        blank=True,
                        default=3000.0,
                        help_text="Static lowpass cutoff (Hz, None = no filter)",
                        null=True,
                    ),
                ),
                (
                    "static_highpass_hz",
                    models.FloatField(
                        blank=True,
                        default=200.0,
                        help_text="Static highpass cutoff (Hz, None = no filter)",
                        null=True,
                    ),
                ),
                (
                    "static_bandwidth_hz",
                    models.FloatField(
                        blank=True,
                        default=None,
                        help_text="Static bandwidth for bandpass (Hz, None = use lowpass/highpass)",
                        null=True,
                    ),
                ),
                (
                    "voice_template",
                    models.CharField(
                        blank=True,
                        help_text="TTS voice model identifier (e.g., 'pilot_male_01', 'controller_female_02')",
                        max_length=100,
                    ),
                ),
                (
                    "voice_pitch_shift_cents",
                    models.IntegerField(
                        default=0,
                        help_text="Pitch adjustment in cents (-1200 to +1200, 0 = no shift)",
                    ),
                ),
                (
                    "voice_speed_factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Speech speed multiplier (0.5 = half speed, 2.0 = double speed)",
                    ),
                ),
                (
                    "quindar_start_freq_hz",
                    models.FloatField(
                        default=2525.0, help_text="Quindar start tone frequency (Hz)"
                    ),
                ),
                (
                    "quindar_end_freq_hz",
                    models.FloatField(
                        default=2475.0, help_text="Quindar end tone frequency (Hz)"
                    ),
                ),
                (
                    "quindar_gain",
                    models.FloatField(
                        default=0.9, help_text="Quindar tone amplitude (0.0 to 1.0+)"
                    ),
                ),
                (
                    "actor",
                    models.OneToOneField(
                        blank=True,
                        help_text="The Actor this audio profile belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_profile",
                        to="universe.actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio Profile",
                "verbose_name_plural": "Audio Profiles",
            },
        ),
    ]
