# Generated by Django 5.1.6 on 2025-12-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0017_add_audio_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audioprofile",
            name="engine_rumble_base_freq_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="engine_rumble_harmonics",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="engine_rumble_intensity",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="quindar_end_freq_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="quindar_gain",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="quindar_start_freq_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="reverb_decay_factor",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="reverb_delay_ms",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="reverb_room_size_hint",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="room_tone_enabled",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="static_bandwidth_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="static_highpass_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="static_intensity",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="static_lowpass_hz",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="voice_pitch_shift_cents",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="voice_speed_factor",
        ),
        migrations.RemoveField(
            model_name="audioprofile",
            name="voice_template",
        ),
        migrations.AddField(
            model_name="audioprofile",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Audio parameters as JSON: room_tone, static, quindar, voiceprint, etc.",
            ),
        ),
    ]
