# Generated by Django 5.1.6 on 2025-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0018_refactor_audio_profile_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogueeventlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional event metadata (e.g., modem_data for nav broadcasts)",
            ),
        ),
    ]
