# Generated by Django 5.1.6 on 2025-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0019_add_metadata_to_dialogue_event_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="orbital_distance_km",
            field=models.FloatField(
                blank=True,
                help_text="Orbital distance from parent body surface in km",
                null=True,
            ),
        ),
    ]
