# Generated by Django 5.1.6 on 2025-12-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0020_add_orbital_distance_km_to_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="The Location (Planet, Moon, Star, StarSystem) this satellite orbits",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="satellites",
                to="universe.location",
            ),
        ),
    ]
