# Generated by Django 5.1.6 on 2025-12-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0021_add_location_to_satellite"),
    ]

    operations = [
        migrations.AddField(
            model_name="star",
            name="luminosity_solar",
            field=models.FloatField(
                blank=True, help_text="Luminosity in solar units (L☉)", null=True
            ),
        ),
    ]
