# Generated by Django 5.1.6 on 2025-12-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0022_add_luminosity_solar_to_star"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogueeventlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="The actor speaking this dialogue",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dialogue_events",
                to="universe.actor",
            ),
        ),
        migrations.AlterField(
            model_name="dialogueeventlog",
            name="actor_name",
            field=models.CharField(
                help_text="Name of the speaking actor (cached for display)",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="dialogueeventlog",
            index=models.Index(fields=["actor"], name="universe_di_actor_i_451920_idx"),
        ),
    ]
