# Generated by Django 5.1.6 on 2025-12-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0023_dialogueeventlog_actor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ship",
            name="status",
        ),
    ]
