# Generated by Django 5.1.6 on 2025-12-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0024_remove_ship_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogueeventlog",
            name="audio_file",
            field=models.CharField(
                blank=True,
                help_text="Path to pre-rendered mixed audio file (relative to media root)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dialogueeventlog",
            name="audio_rendered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the audio was pre-rendered by the background worker",
                null=True,
            ),
        ),
    ]
