# Generated by Django 5.1.6 on 2025-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0025_add_audio_pregeneration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogueeventlog",
            name="audio_generating",
            field=models.BooleanField(
                default=False,
                help_text="True if audio is currently being generated (prevents concurrent generation)",
            ),
        ),
    ]
