# Generated by Django 5.1.6 on 2025-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universe", "0026_add_audio_generating_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialogueeventlog",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text="Pre-rendered mixed audio file (managed by Django storage)",
                null=True,
                upload_to="rendered_audio/",
            ),
        ),
    ]
