# Generated by Django 5.1.6 on 2026-03-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universe", "0027_alter_dialogueeventlog_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="orbit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GEO", "Geostationary"),
                    ("HALF_GEO", "Half-Geostationary"),
                    ("L4", "L4 Lagrange Point"),
                    ("L5", "L5 Lagrange Point"),
                    ("LOW", "Low Orbit"),
                    ("CUSTOM", "Custom/Manual"),
                ],
                help_text="How the orbital position was determined (auto-calculated or manual)",
                max_length=8,
                null=True,
            ),
        ),
    ]
