# Generated by Django 5.2.15 on 2026-07-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("universe", "0028_add_station_orbit_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavBroadcastSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.FloatField(
                        help_text="Reserved simulation-time broadcast slot (on-the-hour)",
                        unique=True,
                    ),
                ),
                (
                    "satellite_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Satellite the slot was reserved for (observability only)",
                        max_length=200,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Database insertion time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nav Broadcast Slot",
                "verbose_name_plural": "Nav Broadcast Slots",
                "ordering": ["timestamp"],
            },
        ),
    ]
